/*
IPFS Pinning Service API

Testing PinsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pinionengineering/pinning-service-models"
)

func Test_client_PinsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PinsAPIService AddPin", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PinsAPI.AddPin(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PinsAPIService DeletePinByRequestId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestid string

		httpRes, err := apiClient.PinsAPI.DeletePinByRequestId(context.Background(), requestid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PinsAPIService GetPinByRequestId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestid string

		resp, httpRes, err := apiClient.PinsAPI.GetPinByRequestId(context.Background(), requestid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PinsAPIService GetPins", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PinsAPI.GetPins(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PinsAPIService ReplacePinByRequestId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var requestid string

		resp, httpRes, err := apiClient.PinsAPI.ReplacePinByRequestId(context.Background(), requestid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
